# Generated by Django 4.1.1 on 2022-12-19 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150, verbose_name='Название комании')),
                ('company_name_ru', models.CharField(max_length=150, null=True, verbose_name='Название комании')),
                ('company_name_en', models.CharField(max_length=150, null=True, verbose_name='Название комании')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='URL')),
                ('is_published', models.BooleanField(default=True, verbose_name='Отображение')),
            ],
            options={
                'verbose_name': 'Наименование команий',
                'verbose_name_plural': 'Наименования компаний',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='Equipment_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=150, verbose_name='Название')),
                ('category_name_ru', models.CharField(max_length=150, null=True, verbose_name='Название')),
                ('category_name_en', models.CharField(max_length=150, null=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='URL')),
                ('short_description', models.CharField(max_length=150, verbose_name='Предназанчение')),
                ('short_description_ru', models.CharField(max_length=150, null=True, verbose_name='Предназанчение')),
                ('short_description_en', models.CharField(max_length=150, null=True, verbose_name='Предназанчение')),
                ('full_description', models.TextField(max_length=1500, verbose_name='Полное описание')),
                ('full_description_ru', models.TextField(max_length=1500, null=True, verbose_name='Полное описание')),
                ('full_description_en', models.TextField(max_length=1500, null=True, verbose_name='Полное описание')),
                ('is_published', models.BooleanField(default=True, verbose_name='Отображение')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.company', verbose_name='Комания')),
            ],
            options={
                'verbose_name': 'Категория оборудования',
                'verbose_name_plural': 'Категории оборудования',
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='Equipment_Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=150, verbose_name='Название')),
                ('class_name_ru', models.CharField(max_length=150, null=True, verbose_name='Название')),
                ('class_name_en', models.CharField(max_length=150, null=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='URL')),
                ('short_description', models.CharField(max_length=150, verbose_name='Предназанчение')),
                ('short_description_ru', models.CharField(max_length=150, null=True, verbose_name='Предназанчение')),
                ('short_description_en', models.CharField(max_length=150, null=True, verbose_name='Предназанчение')),
                ('full_description', models.TextField(max_length=1500, verbose_name='Полное описание')),
                ('full_description_ru', models.TextField(max_length=1500, null=True, verbose_name='Полное описание')),
                ('full_description_en', models.TextField(max_length=1500, null=True, verbose_name='Полное описание')),
                ('img', models.ImageField(blank=True, null=True, upload_to='equipment_class_uploads', verbose_name='Изображение')),
                ('is_published', models.BooleanField(default=True, verbose_name='Отображение')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.company', verbose_name='Комания')),
            ],
            options={
                'verbose_name': 'Класс оборудования',
                'verbose_name_plural': 'Классы оборудования',
                'ordering': ['class_name'],
            },
        ),
        migrations.CreateModel(
            name='Equipment_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=150, verbose_name='Название')),
                ('item_name_ru', models.CharField(max_length=150, null=True, verbose_name='Название')),
                ('item_name_en', models.CharField(max_length=150, null=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='URL')),
                ('short_description', models.CharField(max_length=150, verbose_name='Предназанчение')),
                ('short_description_ru', models.CharField(max_length=150, null=True, verbose_name='Предназанчение')),
                ('short_description_en', models.CharField(max_length=150, null=True, verbose_name='Предназанчение')),
                ('full_description', models.TextField(max_length=1500, verbose_name='Полное описание')),
                ('full_description_ru', models.TextField(max_length=1500, null=True, verbose_name='Полное описание')),
                ('full_description_en', models.TextField(max_length=1500, null=True, verbose_name='Полное описание')),
                ('is_published', models.BooleanField(default=True, verbose_name='Отображение')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.company', verbose_name='Комания')),
                ('equipment_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.equipment_category', verbose_name='Категория')),
                ('equipment_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.equipment_class', verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Наименование оборудования',
                'verbose_name_plural': 'Наименования оборудования',
                'ordering': ['item_name'],
            },
        ),
        migrations.AddField(
            model_name='equipment_category',
            name='equipment_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.equipment_class', verbose_name='Класс'),
        ),
        migrations.CreateModel(
            name='Equipment_Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessory_name', models.CharField(max_length=150, verbose_name='Название')),
                ('accessory_name_ru', models.CharField(max_length=150, null=True, verbose_name='Название')),
                ('accessory_name_en', models.CharField(max_length=150, null=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='URL')),
                ('short_description', models.CharField(max_length=150, verbose_name='Предназанчение')),
                ('short_description_ru', models.CharField(max_length=150, null=True, verbose_name='Предназанчение')),
                ('short_description_en', models.CharField(max_length=150, null=True, verbose_name='Предназанчение')),
                ('full_description', models.TextField(max_length=1500, verbose_name='Полное описание')),
                ('full_description_ru', models.TextField(max_length=1500, null=True, verbose_name='Полное описание')),
                ('full_description_en', models.TextField(max_length=1500, null=True, verbose_name='Полное описание')),
                ('is_published', models.BooleanField(default=True, verbose_name='Отображение')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.company', verbose_name='Комания')),
                ('equipment', models.ManyToManyField(to='main_site.equipment_item', verbose_name='Oборудование')),
            ],
            options={
                'verbose_name': 'Наименование аксессуара',
                'verbose_name_plural': 'Наименования аксессуаров',
                'ordering': ['accessory_name'],
            },
        ),
    ]
