# Generated by Django 4.1.1 on 2022-12-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='equipment_category',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Предназанчение'),
        ),
        migrations.AlterField(
            model_name='equipment_item',
            name='item_name',
            field=models.CharField(max_length=150, verbose_name='Oборудование'),
        ),
        migrations.AlterField(
            model_name='equipment_item',
            name='item_name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Oборудование'),
        ),
        migrations.AlterField(
            model_name='equipment_item',
            name='item_name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Oборудование'),
        ),
    ]
