# Generated by Django 4.1.4 on 2023-01-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='head_img',
            field=models.ImageField(upload_to='news_uploads', verbose_name='Главное изображение'),
        ),
    ]
