# Generated by Django 4.1.1 on 2023-01-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_images',
            name='additional_imgs',
            field=models.ImageField(blank=True, upload_to='news_uploads', verbose_name='Дополнительные изображения в новости'),
        ),
    ]
