# Generated by Django 4.1.1 on 2023-01-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0002_alter_news_images_additional_imgs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_head_img',
            field=models.ImageField(upload_to='companies_uploads', verbose_name='Главное изображение'),
        ),
    ]
