# Generated by Django 4.1.1 on 2022-12-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0002_alter_equipment_acessory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment_acessory',
            name='acessory_name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Название оборудования'),
        ),
        migrations.AddField(
            model_name='equipment_acessory',
            name='acessory_name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Название оборудования'),
        ),
        migrations.AddField(
            model_name='equipment_acessory',
            name='full_description_en',
            field=models.TextField(max_length=1500, null=True, verbose_name='Полное описание оборудования'),
        ),
        migrations.AddField(
            model_name='equipment_acessory',
            name='full_description_ru',
            field=models.TextField(max_length=1500, null=True, verbose_name='Полное описание оборудования'),
        ),
        migrations.AddField(
            model_name='equipment_acessory',
            name='short_description_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Предназанчение оборудования'),
        ),
        migrations.AddField(
            model_name='equipment_acessory',
            name='short_description_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Предназанчение оборудования'),
        ),
    ]
