# Generated by Django 4.1.1 on 2022-12-22 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0002_alter_company_company_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['company_name'], 'verbose_name': 'Комания', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AlterModelOptions(
            name='equipment_accessory',
            options={'ordering': ['accessory_name'], 'verbose_name': 'Атрибут объекта', 'verbose_name_plural': 'Атрибуты объектов'},
        ),
        migrations.AlterModelOptions(
            name='equipment_category',
            options={'ordering': ['category_name'], 'verbose_name': 'Категория данных', 'verbose_name_plural': 'Категории данных'},
        ),
        migrations.AlterModelOptions(
            name='equipment_class',
            options={'ordering': ['class_name'], 'verbose_name': 'Класс данных', 'verbose_name_plural': 'Классы данных'},
        ),
        migrations.AlterModelOptions(
            name='equipment_item',
            options={'ordering': ['item_name'], 'verbose_name': 'Объект данных', 'verbose_name_plural': 'Объекты данных'},
        ),
        migrations.RemoveField(
            model_name='equipment_class',
            name='img',
        ),
        migrations.AddField(
            model_name='company',
            name='head_img',
            field=models.ImageField(blank=True, null=True, upload_to='companies_uploads', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='equipment_accessory',
            name='head_img',
            field=models.ImageField(blank=True, null=True, upload_to='attributes_uploads', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='equipment_category',
            name='head_img',
            field=models.ImageField(blank=True, null=True, upload_to='categories_uploads', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='equipment_class',
            name='head_img',
            field=models.ImageField(blank=True, null=True, upload_to='classes_uploads', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='equipment_item',
            name='head_img',
            field=models.ImageField(blank=True, null=True, upload_to='objects_uploads', verbose_name='Изображение'),
        ),
    ]
