# Generated by Django 4.1.4 on 2023-01-05 09:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0002_alter_news_head_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='body1',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Тескт статьи до карусели дополнительных изображений', null=True, verbose_name='Содержание статьи'),
        ),
        migrations.AlterField(
            model_name='news',
            name='body2',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Тескт статьи после карусели дополнительных изображений', null=True, verbose_name='Содержание статьи'),
        ),
    ]
