# Generated by Django 4.1.1 on 2023-01-06 12:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0003_alter_company_company_head_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment_category',
            name='full_description',
            field=ckeditor.fields.RichTextField(max_length=1500, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='equipment_category',
            name='full_description_en',
            field=ckeditor.fields.RichTextField(max_length=1500, null=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='equipment_category',
            name='full_description_ru',
            field=ckeditor.fields.RichTextField(max_length=1500, null=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='equipment_class',
            name='full_description',
            field=ckeditor.fields.RichTextField(max_length=1500, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='equipment_class',
            name='full_description_en',
            field=ckeditor.fields.RichTextField(max_length=1500, null=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='equipment_class',
            name='full_description_ru',
            field=ckeditor.fields.RichTextField(max_length=1500, null=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='equipment_item',
            name='full_description',
            field=ckeditor.fields.RichTextField(max_length=1500, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='equipment_item',
            name='full_description_en',
            field=ckeditor.fields.RichTextField(max_length=1500, null=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='equipment_item',
            name='full_description_ru',
            field=ckeditor.fields.RichTextField(max_length=1500, null=True, verbose_name='Полное описание'),
        ),
    ]
