# Generated by Django 4.1.1 on 2022-12-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0003_alter_company_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='priority',
            field=models.CharField(max_length=3, null=True, verbose_name='Приоритет отображения'),
        ),
    ]
