# Generated by Django 4.1.1 on 2022-12-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0004_company_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='priority',
            field=models.DecimalField(decimal_places=0, help_text='Определяет очередность отображения информации на странице (1 - 99).', max_digits=2, null=True, verbose_name='Приоритет отображения'),
        ),
    ]
