# Generated by Django 4.1.1 on 2023-01-06 12:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0004_alter_equipment_category_full_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment_accessory',
            name='full_description',
            field=models.TextField(verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='equipment_accessory',
            name='full_description_en',
            field=models.TextField(null=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='equipment_accessory',
            name='full_description_ru',
            field=models.TextField(null=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='equipment_accessory',
            name='specifications',
            field=models.TextField(blank=True, null=True, verbose_name='Технические характеристики'),
        ),
        migrations.AlterField(
            model_name='equipment_accessory',
            name='specifications_en',
            field=models.TextField(blank=True, null=True, verbose_name='Технические характеристики'),
        ),
        migrations.AlterField(
            model_name='equipment_accessory',
            name='specifications_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Технические характеристики'),
        ),
        migrations.AlterField(
            model_name='equipment_category',
            name='full_description',
            field=ckeditor.fields.RichTextField(verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='equipment_category',
            name='full_description_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='equipment_category',
            name='full_description_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='equipment_class',
            name='full_description',
            field=ckeditor.fields.RichTextField(verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='equipment_class',
            name='full_description_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='equipment_class',
            name='full_description_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='equipment_item',
            name='full_description',
            field=ckeditor.fields.RichTextField(verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='equipment_item',
            name='full_description_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='equipment_item',
            name='full_description_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Полное описание'),
        ),
    ]
