# Generated by Django 4.1.1 on 2023-01-06 15:00

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0005_alter_equipment_accessory_full_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment_accessory',
            name='product_head_img',
            field=models.ImageField(blank=True, help_text='Изображение класса, категории или самой продукции (если не выбрано, то используется "заглушка")', null=True, upload_to='attributes_uploads', verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='equipment_category',
            name='product_head_img',
            field=models.ImageField(blank=True, help_text='Изображение класса, категории или самой продукции (если не выбрано, то используется "заглушка")', null=True, upload_to='categories_uploads', verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='equipment_class',
            name='product_head_img',
            field=models.ImageField(blank=True, help_text='Изображение класса, категории или самой продукции (если не выбрано, то используется "заглушка")', null=True, upload_to='classes_uploads', verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='equipment_item',
            name='product_head_img',
            field=models.ImageField(blank=True, help_text='Изображение класса, категории или самой продукции (если не выбрано, то используется "заглушка")', null=True, upload_to='objects_uploads', verbose_name='Главное изображение'),
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='URL')),
                ('contact_data', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Контактные данные')),
                ('contact_data_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Контактные данные')),
                ('contact_data_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Контактные данные')),
                ('is_published', models.BooleanField(default=True, help_text='Отображение данных на странице сайта.', verbose_name='Отображение')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.company', verbose_name='Комания')),
            ],
            options={
                'verbose_name': 'Контактные данные',
                'verbose_name_plural': 'Контактные данные',
                'ordering': ['company'],
            },
        ),
    ]
