# Generated by Django 4.1.1 on 2022-12-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0005_alter_company_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment_accessory',
            name='specifications',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Технические характеристики'),
        ),
        migrations.AddField(
            model_name='equipment_accessory',
            name='specifications_en',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Технические характеристики'),
        ),
        migrations.AddField(
            model_name='equipment_accessory',
            name='specifications_ru',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Технические характеристики'),
        ),
        migrations.AddField(
            model_name='equipment_item',
            name='specifications',
            field=models.TextField(max_length=3000, null=True, verbose_name='Технические характеристики'),
        ),
        migrations.AddField(
            model_name='equipment_item',
            name='specifications_en',
            field=models.TextField(max_length=3000, null=True, verbose_name='Технические характеристики'),
        ),
        migrations.AddField(
            model_name='equipment_item',
            name='specifications_ru',
            field=models.TextField(max_length=3000, null=True, verbose_name='Технические характеристики'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Отображение данных на странице сайта.', verbose_name='Отображение'),
        ),
        migrations.AlterField(
            model_name='company',
            name='priority',
            field=models.DecimalField(decimal_places=0, help_text='Определяет очередность отображения информации на странице сайта (1 - 99).', max_digits=2, null=True, verbose_name='Приоритет отображения'),
        ),
        migrations.AlterField(
            model_name='equipment_accessory',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Отображение данных на странице сайта.', verbose_name='Отображение'),
        ),
        migrations.AlterField(
            model_name='equipment_category',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Отображение данных на странице сайта.', verbose_name='Предназанчение'),
        ),
        migrations.AlterField(
            model_name='equipment_class',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Отображение данных на странице сайта.', verbose_name='Отображение'),
        ),
        migrations.AlterField(
            model_name='equipment_item',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Отображение данных на странице сайта.', verbose_name='Отображение'),
        ),
    ]
