# Generated by Django 4.1.4 on 2023-01-09 09:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0006_alter_equipment_accessory_product_head_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment_accessory',
            name='full_description',
            field=ckeditor.fields.RichTextField(verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='equipment_accessory',
            name='full_description_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='equipment_accessory',
            name='full_description_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='equipment_accessory',
            name='specifications',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Технические характеристики'),
        ),
        migrations.AlterField(
            model_name='equipment_accessory',
            name='specifications_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Технические характеристики'),
        ),
        migrations.AlterField(
            model_name='equipment_accessory',
            name='specifications_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Технические характеристики'),
        ),
    ]
