# Generated by Django 4.1.4 on 2023-01-04 12:40

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0007_alter_equipment_item_specifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='head_img',
            field=models.ImageField(blank=True, null=True, upload_to='companies_uploads', verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='equipment_accessory',
            name='head_img',
            field=models.ImageField(blank=True, null=True, upload_to='attributes_uploads', verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='equipment_category',
            name='head_img',
            field=models.ImageField(blank=True, null=True, upload_to='categories_uploads', verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='equipment_class',
            name='head_img',
            field=models.ImageField(blank=True, null=True, upload_to='classes_uploads', verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='equipment_item',
            name='head_img',
            field=models.ImageField(blank=True, null=True, upload_to='objects_uploads', verbose_name='Главное изображение'),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_img', models.ImageField(blank=True, null=True, upload_to='attributes_uploads', verbose_name='Главное изображение')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=150, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=150, null=True, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='URL')),
                ('body1', ckeditor.fields.RichTextField(help_text='Тескт статьи до карусели дополнительных изображений', null=True, verbose_name='Содержание статьи')),
                ('body1_ru', ckeditor.fields.RichTextField(help_text='Тескт статьи до карусели дополнительных изображений', null=True, verbose_name='Содержание статьи')),
                ('body1_en', ckeditor.fields.RichTextField(help_text='Тескт статьи до карусели дополнительных изображений', null=True, verbose_name='Содержание статьи')),
                ('additional_imgs', models.ImageField(blank=True, null=True, upload_to='attributes_uploads', verbose_name='Дополнительные зображения')),
                ('body2', ckeditor.fields.RichTextField(help_text='Тескт статьи после карусели дополнительных изображений', null=True, verbose_name='Содержание статьи')),
                ('body2_ru', ckeditor.fields.RichTextField(help_text='Тескт статьи после карусели дополнительных изображений', null=True, verbose_name='Содержание статьи')),
                ('body2_en', ckeditor.fields.RichTextField(help_text='Тескт статьи после карусели дополнительных изображений', null=True, verbose_name='Содержание статьи')),
                ('file', models.FileField(blank=True, null=True, upload_to='item_uploads')),
                ('issued', models.DateTimeField()),
                ('is_published', models.BooleanField(default=True, help_text='Отображение данных на странице сайта.', verbose_name='Отображение')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.company', verbose_name='Комания')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['issued'],
            },
        ),
    ]
