# Generated by Django 4.1.4 on 2023-01-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0008_alter_company_head_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='additional_imgs',
            field=models.ImageField(blank=True, null=True, upload_to='news_uploads', verbose_name='Дополнительные зображения'),
        ),
        migrations.AlterField(
            model_name='news',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='news_uploads'),
        ),
        migrations.AlterField(
            model_name='news',
            name='head_img',
            field=models.ImageField(blank=True, null=True, upload_to='news_uploads', verbose_name='Главное изображение'),
        ),
    ]
