# Generated by Django 4.1.4 on 2023-01-04 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0009_alter_news_additional_imgs_alter_news_file_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='Company_News',
        ),
        migrations.AlterModelOptions(
            name='company_news',
            options={'ordering': ['issued'], 'verbose_name': 'Атрибут объекта', 'verbose_name_plural': 'Атрибуты объектов'},
        ),
    ]
