# Generated by Django 4.1.4 on 2023-01-04 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0010_rename_news_company_news_alter_company_news_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company_News',
            new_name='News',
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['issued'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
