# Generated by Django 4.1.4 on 2023-01-04 15:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0011_rename_company_news_news_alter_news_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='body2',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Тескт статьи после карусели дополнительных изображений', null=True, verbose_name='Содержание статьи'),
        ),
        migrations.AlterField(
            model_name='news',
            name='body2_en',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Тескт статьи после карусели дополнительных изображений', null=True, verbose_name='Содержание статьи'),
        ),
        migrations.AlterField(
            model_name='news',
            name='body2_ru',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Тескт статьи после карусели дополнительных изображений', null=True, verbose_name='Содержание статьи'),
        ),
    ]
