# Generated by Django 4.1.1 on 2022-12-08 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment_acessory',
            options={'ordering': ['acessory_name'], 'verbose_name': 'Наименование аксессуара', 'verbose_name_plural': 'Наименования аксессуаров'},
        ),
        migrations.AddField(
            model_name='equipment_acessory',
            name='acessory_name',
            field=models.CharField(max_length=150, null=True, verbose_name='Название оборудования'),
        ),
        migrations.AddField(
            model_name='equipment_acessory',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_site.company', verbose_name='Комания'),
        ),
        migrations.AddField(
            model_name='equipment_acessory',
            name='equipment',
            field=models.ManyToManyField(null=True, to='main_site.equipment_item', verbose_name='Oборудование'),
        ),
        migrations.AddField(
            model_name='equipment_acessory',
            name='full_description',
            field=models.TextField(max_length=1500, null=True, verbose_name='Полное описание оборудования'),
        ),
        migrations.AddField(
            model_name='equipment_acessory',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Отображение'),
        ),
        migrations.AddField(
            model_name='equipment_acessory',
            name='short_description',
            field=models.CharField(max_length=150, null=True, verbose_name='Предназанчение оборудования'),
        ),
    ]
